<?php

namespace Infuse\DictionaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
    public function findAllStartWith($letter, $status = 1) {
        return $this->getEntityManager()
            ->createQuery('SELECT w FROM InfuseDictionaryBundle:Word w WHERE w.status = :status AND w.word LIKE :letter ORDER BY w.word ASC')
            ->setParameter('status', $status)
            ->setParameter('letter', $letter . '%')
            ->getResult();
    }

    public function searchAllWithSlugText($text, $status = 1)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT w FROM InfuseDictionaryBundle:Word w WHERE w.status = :status AND w.slug LIKE :search ORDER BY w.word ASC')
            ->setParameter('status', $status)
            ->setParameter('search', $text . '%')
            ->getResult();
    }
}
